name: CI #1 - Feature Validation

on:
  push:
    branches:
      - 'feature/*'

concurrency:
  group: ci-feature-${{ github.ref }}
  cancel-in-progress: true

jobs:

  setup:
    name: Setup and Validate Environment
    uses: ./.github/workflows/android-ci-base.yml

  build-feature:

    name: Build Feature Branch

    runs-on: ubuntu-latest

    needs: setup

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace
