name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (ex: 1.2)"
        required: true

permissions:
  contents: write

jobs:

  create-release:

    name: Create Release Branch

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set-version.outputs.version }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set version
        id: set-version
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate version input
        run: |
          VERSION=${{ steps.set-version.outputs.version }}

          if [[ $VERSION == release/* ]]; then
            echo "❌ Informe apenas a versão (ex: 1.2)"
            exit 1
          fi

      - name: Check if release already exists
        run: |
          VERSION=${{ steps.set-version.outputs.version }}

          if git ls-remote --exit-code --heads origin release/$VERSION; then
            echo "❌ release/$VERSION já existe"
            exit 1
          fi

      - name: Fetch branches
        run: git fetch origin

      - name: Create release branch
        run: |
          VERSION=${{ steps.set-version.outputs.version }}

          git checkout -b release/$VERSION origin/dev
          git push origin release/$VERSION

  build-release:

    name: Build Release

    needs: create-release

    uses: ./.github/workflows/build-artifact.yml

    with:
      # opcional, caso você queira passar a versão
      version: ${{ needs.create-release.outputs.version }}
