name: CI #2 - DEV Integration

on:
  push:
    branches: [ dev ]

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Dar permissão ao Gradle
        run: chmod +x ./gradlew

      - name: Build DEV (Debug)
        run: ./gradlew assembleDebug

      - name: Upload APK DEV
        uses: actions/upload-artifact@v4
        with:
          name: apk-dev-debug
          path: app/build/outputs/apk/debug/*.apk



          - name: Validar origem do PR (feature/* → dev)
  if: github.event_name == 'pull_request'
  run: |
    BASE="${{ github.base_ref }}"
    HEAD="${{ github.head_ref }}"

    if [[ "$BASE" != "dev" ]]; then
      exit 0
    fi

    if [[ ! "$HEAD" =~ ^feature/ ]]; then
      echo "ERRO: PR para 'dev' deve ter origem em 'feature/*'"
      exit 1
    fi
