name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Create release branch
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}
