name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (ex: 1.2)"
        required: true

permissions:
  contents: write

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Validate version input
        run: |
          VERSION=${{ github.event.inputs.version }}

          if [[ $VERSION == release/* ]]; then
            echo "❌ Informe apenas a versão (ex: 1.2), não use 'release/'."
            exit 1
          fi

          echo "✅ Versão informada: $VERSION"

      - name: Check if release branch already exists
        run: |
          VERSION=${{ github.event.inputs.version }}

          if git ls-remote --exit-code --heads origin release/$VERSION; then
            echo "❌ Branch release/$VERSION já existe."
            exit 1
          else
            echo "✅ Branch release/$VERSION não existe. Continuando."
          fi

      - name: Fetch latest branches
        run: git fetch origin

      - name: Create release branch from origin/dev
        run: |
          VERSION=${{ github.event.inputs.version }}

          git checkout -b release/$VERSION origin/dev
          git push origin release/$VERSION

      - name: Success
        run: echo "✅ Release release/${{ github.event.inputs.version }} criada com sucesso."
